In [11]:
#broadcasting is like SCALAR MULTIPLICATION its a shorter and faster method
import numpy as np
a=np.array([[1,2,3,4]])
b=2
a*b

array([[2, 4, 6, 8]])

In [19]:
#reshaping N:B when reshaping, the shape u are want to reshape to must be equal to the number of items
x=np.arange(4)
print(x)
print(x.reshape(4,1))

[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]


In [35]:
y=np.arange(6)
print(y)
z=y.reshape(2,3)
z.shape

[0 1 2 3 4 5]


(2, 3)

In [37]:
x=np.arange(4)
y=np.ones(5)
xx=x.reshape(4,1)
xx+y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [38]:
x=np.arange(4)
y=np.ones(5)
yy=y.reshape(5,1)
yy+x

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [43]:
x=np.arange(4)
z=np.ones((3,4))
#print(z)
z+x

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])