In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x=np.array([5,15,25,35,45,55]).reshape((-1,1))
y=np.array([5,20,14,32,22,38])

In [5]:
print(x,'\n',  x.shape)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]] 
 (6, 1)


In [6]:
# instantiating the model
model=LinearRegression()

In [7]:
model.fit(x,y)
# or linearRegression().fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
r_sq=model.score(x,y)
print('coefficient of determination:',r_sq)

coefficient of determination: 0.7158756137479542


In [15]:
print('intercept:',model.intercept_)

intercept: 5.633333333333329


In [16]:
print('slope:',model.coef_)

slope: [0.54]


In [21]:
#B0+B1x+B2x
# where B0 is intercept and B1,B2..... are representing the slope
v=5.63+(0.54*15)
v

13.73

In [23]:
y_pred=model.predict(x)

print('predicted response:',y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [24]:
import pandas as pd
pred_vs_actual= pd.DataFrame({'Predicted': np.array(y_pred), 'Actual':y})

C:\Users\Esewi\AppData\Local\Python\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\Esewi\AppData\Local\Python\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [25]:
pred_vs_actual

Predicted  Actual
0   8.333333       5
1  13.733333      20
2  19.133333      14
3  24.533333      32
4  29.933333      22
5  35.333333      38

##### Multilinear Regression

In [11]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [12]:
x=[[0,1],[5,1],[15,2],[25,5],[35,11],[45,15],[55,34],[60,35]]
y=[4,5,20,14,32,22,38,43]

In [13]:
x,y=np.array(x),np.array(y)

In [14]:
print(x)

[[ 0  1]
 [ 5  1]
 [15  2]
 [25  5]
 [35 11]
 [45 15]
 [55 34]
 [60 35]]


In [15]:
print(y)

[ 4  5 20 14 32 22 38 43]


In [19]:
md=pd.DataFrame(x,columns=['x1','x2'])
md

x1  x2
0   0   1
1   5   1
2  15   2
3  25   5
4  35  11
5  45  15
6  55  34
7  60  35

In [20]:
model=LinearRegression().fit(x,y)

In [21]:
r_sq=model.score(x,y)
print('coefficient of determination:',r_sq)

print('slope:',model.coef_)

coefficient of determination: 0.8615939258756776
slope: [0.44706965 0.25502548]


In [22]:
print('intercept:',model.intercept_)

intercept: 5.5225792751981935


In [24]:
y_pred=model.predict(x)
print('predicted response:',y_pred,sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [25]:
pred_vs_actual2= pd.DataFrame({'Predicted': np.array(y_pred), 'Actual':y})
pred_vs_actual2

Predicted  Actual
0   5.777605       4
1   8.012953       5
2  12.738675      20
3  17.974448      14
4  23.975297      32
5  29.466096      22
6  38.782276      38
7  41.272650      43

#### Polynomial Regression

In [26]:
from sklearn.preprocessing import PolynomialFeatures

In [27]:
x=np.array([5,15,25,35,45,55]).reshape((-1,1))
y=np.array([15,11,2,8,25,32])

In [29]:
x_=PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [32]:
print(x_)

[[   5.   25.]
 [  15.  225.]
 [  25.  625.]
 [  35. 1225.]
 [  45. 2025.]
 [  55. 3025.]]


In [33]:
model=LinearRegression().fit(x_,y)

In [34]:
r_sq=model.score(x_,y)
print('coefficient of determination:',r_sq)

coefficient of determination: 0.8908516262498564


In [35]:
print('intercept:',model.intercept_)

intercept: 21.372321428571453


In [36]:
print('slope:',model.coef_)

slope: [-1.32357143  0.02839286]


In [37]:
y_pred=model.predict(x_)
print('predicted response:',y_pred,sep='\n')

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


In [38]:
pred_vs_actual3= pd.DataFrame({'Predicted': np.array(y_pred), 'Actual':y})
pred_vs_actual3

Predicted  Actual
0  15.464286      15
1   7.907143      11
2   6.028571       2
3   9.828571       8
4  19.307143      25
5  34.464286      32